# Generated by Django 4.1.5 on 2023-01-09 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userextend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
